# Generated by Django 5.0.6 on 2024-05-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Full Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('othername', models.CharField(max_length=100, verbose_name='Full Name')),
                ('course', models.CharField(max_length=100, verbose_name='Course')),
                ('country_code', models.IntegerField(verbose_name='Country Code')),
                ('matric_number', models.CharField(max_length=50, verbose_name='Matriculation Number')),
                ('number', models.IntegerField(verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
