# Generated by Django 5.0.6 on 2024-06-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_last_accessed_alter_user_othername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last Seen'),
        ),
    ]
