# Generated by Django 5.0.6 on 2024-06-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_last_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(max_length=1000, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='othername',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Name'),
        ),
    ]
