# Generated by Django 5.0.6 on 2024-06-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_number_alter_user_othername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.BigIntegerField(verbose_name='Phone Number'),
        ),
    ]
