# Generated by Django 5.0.6 on 2024-06-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_email_alter_user_matric_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='u', max_length=50, verbose_name='Role'),
        ),
    ]
