# Generated by Django 5.0.6 on 2024-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_last_accessed_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Course Code')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
            ],
        ),
    ]
