# Generated by Django 5.0.6 on 2024-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Faculty Code')),
                ('name', models.CharField(max_length=100, verbose_name='Faculty Name')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculty_code',
            field=models.CharField(default='', max_length=100, verbose_name='Faculty'),
            preserve_default=False,
        ),
    ]
