# Generated by Django 5.0.6 on 2024-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_faculty_course_faculty_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(db_column='surname', max_length=100, verbose_name='Surname'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Faculty Code'),
        ),
    ]
