# Generated by Django 5.0.6 on 2024-06-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_surname_rename_surname_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Lastname'),
        ),
    ]
