# Generated by Django 5.0.6 on 2024-06-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspended',
            field=models.BooleanField(default=False, verbose_name='Suspended'),
        ),
    ]
