# Generated by Django 5.0.6 on 2024-06-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_exam_alter_user_last_accessed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
