# Generated by Django 5.0.6 on 2024-06-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_exam_done_exam_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_end',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_start',
        ),
        migrations.AlterField(
            model_name='exam',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Exam Label'),
        ),
    ]
